FROM bde2020/spark-master:3.3.0-hadoop3.3

USER root

RUN apk add --no-cache python3 py3-pip && \
    ln -sf python3 /usr/bin/python && \
    ln -sf pip3 /usr/bin/pip

RUN pip install kafka-python hdfs

WORKDIR /app
# Ne pas remettre USER spark ici